apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-eks-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dprateek1991/cloudninja_fiverr.git
    targetRevision: main
    path: helm-chart
    helm:
      valueFiles: 
      - values.yaml
  destination:
    server: https://123456789.gr7.us-east-1.eks.amazonaws.com
    namespace: web-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: false 