apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-eks-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Cloudninja486705/mp-argo_1.git
    targetRevision: main
    path: helm-chart
    helm:
      valueFiles: 
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: web-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: false 